#!/bin/bash
# wait-for-postgres

set -e

until psql -h "$host" -U "postgres" -c '\l' >/dev/null 2>&1; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - ready to execute commands"
